name: Deploy AKS with Azure Policy add-on

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.4"

      - name: Terraform Init
        uses: hashicorp/terraform-action@v2
        with:
          args: init

      - name: Terraform Plan
        uses: hashicorp/terraform-action@v2
        with:
          args: plan

      - name: Terraform Apply
        uses: hashicorp/terraform-action@v2
        with:
          args: apply -auto-approve